// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoStudioMVC.Data;

#nullable disable

namespace PhoStudioMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331091735_AddPhotographerAssignment")]
    partial class AddPhotographerAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "admin_seed_1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@phostudio.com",
                            FullName = "System Administrator",
                            PasswordHash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Phone = "0901123456",
                            Role = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.Booking", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotographerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicePackageId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PhotographerId");

                    b.HasIndex("ServicePackageId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.CloudAlbum", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecureOTP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("CloudAlbums");
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.ServicePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServicePackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Chụp hình kỷ yếu ngoại cảnh 1 buổi",
                            IsActive = true,
                            Name = "Gói Kỷ yếu Cơ Bản",
                            Price = 1500000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phóng sự cưới cao cấp nửa ngày",
                            IsActive = true,
                            Name = "Gói Phóng Sự Cưới",
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chụp chân dung nghệ thuật trong Studio",
                            IsActive = true,
                            Name = "Gói Nàng Thơ",
                            Price = 3000000m
                        });
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.Booking", b =>
                {
                    b.HasOne("PhoStudioMVC.Models.Entities.ApplicationUser", "Client")
                        .WithMany("ClientBookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PhoStudioMVC.Models.Entities.ApplicationUser", "Photographer")
                        .WithMany("PhotographerBookings")
                        .HasForeignKey("PhotographerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PhoStudioMVC.Models.Entities.ServicePackage", "ServicePackage")
                        .WithMany()
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Photographer");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.CloudAlbum", b =>
                {
                    b.HasOne("PhoStudioMVC.Models.Entities.Booking", "Booking")
                        .WithMany("CloudAlbums")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ClientBookings");

                    b.Navigation("PhotographerBookings");
                });

            modelBuilder.Entity("PhoStudioMVC.Models.Entities.Booking", b =>
                {
                    b.Navigation("CloudAlbums");
                });
#pragma warning restore 612, 618
        }
    }
}
